### PR TITLE
Prevent realism from loading on the client if VR is enabled.

### PR DESCRIPTION
**Pull request by Thomasluigi07**
Many games use custom VR scripts, and there is also a different camera in VR. If the game has Realism and it also has custom VR scripts it can break, depending on what the developer has added. This changes Realism to check if game.VRService.VREnabled is true, and if it is, then not do anything to prevent any issues. Some developers don't know how to do this as Roblox's documentation on VR is very limited, so this can help the people who are trying to figure this out and save some time wasted finding the fix. Realism works as intended normally in VR when there is no changes, but can break as soon as you change how VR works (especially the camera). This is a very small fix. I'm not sure how to stop scripts, so I just put the rest of the code after the starting comments in the "else" part of the If, therefore preventing it from running if it's true. If you have a better way of doing it, please do so.
(This deletes the original Realism.rbxm and replaces it with the new version, since I cannot directly edit the file off github.)

### CODE REVIEW

**Comment by sasial-dev** [comment]
FYI, you've got a merge conflict. Also you need to updates the `.lua` as well.

**Comment by Thomasluigi07** [comment]
@sasial-dev it seems that when i replace the RBXL it doesn't seem to let me merge easily, i'll remove the RBXM for now, hope clone does the building for me

**Comment by MaximumADHD** [comment]
Sorry I ghosted this, had to overcome the hurdle of refactoring realism before I wanted to lay any fingers on it again. You may need to reconstruct this pull request.

**Comment by Thomasluigi07** [comment]
I don't really do Roblox development stuff anymore now, so I'm closing this PR.

**Pull request closed without merging**
